In [2]:
import pandas as pd
df=pd.read_csv("/content/loan_approval_1000.csv")

In [ ]:
df

     Age    Income  Loan_Amount  Credit_Score Employment_Type  Loan_Approved
0     59   77761.0       417505           337        Salaried              0
1     49  141178.0       328226           487        Salaried              0
2     35   56368.0       312805           356   Self-Employed              0
3     28   26783.0       218484           319        Salaried              0
4     41  131530.0       315064           572   Self-Employed              0
..   ...       ...          ...           ...             ...            ...
995   58  112447.0       259717           572      Unemployed              0
996   22  134994.0       314167           544      Unemployed              0
997   27  109899.0       169654           749        Salaried              1
998   38   40049.0       240868           546      Unemployed              0
999   47   95717.0       130073           819        Salaried              1

[1000 rows x 6 columns]

In [3]:
df.isnull().sum()

Age                 0
Income             50
Loan_Amount         0
Credit_Score        0
Employment_Type    50
Loan_Approved       0
dtype: int64

In [4]:
df["Income"].fillna(df["Income"].median(), inplace=True)
df["Employment_Type"].fillna(df["Employment_Type"].mode()[0], inplace=True)

df.isnull().sum()

/tmp/ipykernel_4498/1448926426.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Income"].fillna(df["Income"].median(), inplace=True)
/tmp/ipykernel_4498/1448926426.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Employment_Type"].fillna(df["Employment_Type"].mode()[0], inplace=True)

Age                0
Income             0
Loan_Amount        0
Credit_Score       0
Employment_Type    0
Loan_Approved      0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Employment_Type"] = le.fit_transform(df["Employment_Type"])

df.head()

   Age    Income  Loan_Amount  Credit_Score  Employment_Type  Loan_Approved
0   59   77761.0       417505           337                0              0
1   49  141178.0       328226           487                0              0
2   35   56368.0       312805           356                1              0
3   28   26783.0       218484           319                0              0
4   41  131530.0       315064           572                1              0

In [6]:
print(le.classes_)

['Salaried' 'Self-Employed' 'Unemployed']

In [7]:
from sklearn.model_selection import train_test_split

X = df.drop("Loan_Approved", axis=1)
y = df["Loan_Approved"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape

((800, 5), (200, 5))

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = LogisticRegression(random_state=42, max_iter=1000) # Increased max_iter to address ConvergenceWarning
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.79

Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.87      0.85       135
           1       0.70      0.62      0.66        65

    accuracy                           0.79       200
   macro avg       0.76      0.74      0.75       200
weighted avg       0.79      0.79      0.79       200

In [9]:
import pickle

# Save model
pickle.dump(model, open("loan_model.pkl", "wb"))

# Save encoder (IMPORTANT)
pickle.dump(le, open("encoder.pkl", "wb"))

print("Model saved successfully!")

Model saved successfully!